name: SafeCreeper
description: 'Get full control of creatures, players and almost everything!'
main: com.timvisee.safecreeper.SafeCreeper
version: 1.5.2.6
load: startup
author: timvisee
website: http://timvisee.com/
softdepend: [Vault, TVNLib, WorldGuard, Corruption, MobArena, PVPArena, Factions] #hack to fix trove errors
commands:
  safecreeper:
    description: Safe Creeper command
    usage: /safecreeper <arguments>
  sc:
    description: Safe Creeper command
    usage: /sc <arguments>